import type { Metadata } from "next";
import { BoardProvider } from "../contexts/BoardContext";
import { UserProfileProvider } from "../contexts/UserContext";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<BoardProvider>
			<UserProfileProvider>
				<main className='overflow-hidden'>
					<Sidebar />
					<Navbar />
					{children}
				</main>
			</UserProfileProvider>
		</BoardProvider>
	);
}
